apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
  labels:
    app: nodejs-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31487
  selector:
    app: nodejs-app
